// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMFWaHQD-yMoRrNaSXV9XR1VL4Go2i-VQ',
    appId: '1:329133779144:web:cdbe7ac9bc8e5a9c385dfd',
    messagingSenderId: '329133779144',
    projectId: 'byloop-e02ad',
    authDomain: 'byloop-e02ad.firebaseapp.com',
    storageBucket: 'byloop-e02ad.appspot.com',
    measurementId: 'G-QNPMS83D3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAYxaZiWNvWFjjSzgJtJYT5XuefRlTD9o',
    appId: '1:329133779144:android:474e359cabbd39f8385dfd',
    messagingSenderId: '329133779144',
    projectId: 'byloop-e02ad',
    storageBucket: 'byloop-e02ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm8N6Tli4h1ckArJr5_bZ3FXwaBgG1cPE',
    appId: '1:329133779144:ios:a334758ee1747127385dfd',
    messagingSenderId: '329133779144',
    projectId: 'byloop-e02ad',
    storageBucket: 'byloop-e02ad.appspot.com',
    iosBundleId: 'com.example.btloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm8N6Tli4h1ckArJr5_bZ3FXwaBgG1cPE',
    appId: '1:329133779144:ios:898a1017cb42c6a2385dfd',
    messagingSenderId: '329133779144',
    projectId: 'byloop-e02ad',
    storageBucket: 'byloop-e02ad.appspot.com',
    iosBundleId: 'com.example.btloop.RunnerTests',
  );
}
